
-- Now by using the warehouse DB solve the queries: 
USE WAREHOUSE;

-- Queries to Solve:

-- 1. Find the item that has the minimum weight.

SELECT * FROM ITEMS
WHERE WEIGHT = (SELECT MIN(WEIGHT) FROM ITEMS);

-- 2. Find the different warehouses in "Pune".

SELECT * FROM WAREHOUSES 
WHERE CITY = 'PUNE';

-- 3. Find the details of items ordered by a customer named "Mr. Patil".

SELECT C.CNAME, O.ONO, I.ITEMNO, I.DESCRIPTION, OI.ORDERED_QUANTITY  
FROM CUSTOMER C  
JOIN ORDERS O ON C.CNO = O.CUSTOMER_NO   
JOIN ORDERED_ITEMS OI ON O.ONO = OI.ORDER_NO
JOIN ITEMS I ON OI.ITEM_NO = I.ITEMNO
WHERE C.CNAME = 'Mr. Patil'
  
-- 4. Find a Warehouse that has the maximum number of stores.

SELECT W.WID, W.WNAME, W.LOCATION, COUNT(S.SID) AS STORE_COUNT
FROM WAREHOUSES W
LEFT JOIN STORES S ON W.WID = S.WID
GROUP BY W.WID, W.WNAME, W.LOCATION
ORDER BY STORE_COUNT DESC
LIMIT 1;


-- 5. Find an item that is ordered for a minimum number of times.

SELECT I.ITEMNO, I.DESCRIPTION, SUM(OI.ORDERED_QUANTITY) AS TOTAL_ORDERED
FROM ITEMS I
LEFT JOIN ORDERED_ITEMS OI ON I.ITEMNO = OI.ITEM_NO
GROUP BY I.ITEMNO, I.DESCRIPTION
ORDER BY TOTAL_ORDERED ASC
LIMIT 1;

-- 6. Find the detailed orders given by each customer.

SELECT C.CNO, C.CNAME, O.ONO, O.ODATE, I.ITEMNO, I.DESCRIPTION, OI.ORDERED_QUANTITY
FROM CUSTOMER C
JOIN ORDERS O ON C.CNO = O.CUSTOMER_NO
JOIN ORDERED_ITEMS OI ON O.ONO = OI.ORDER_NO
JOIN ITEMS I ON OI.ITEM_NO = I.ITEMNO
ORDER BY C.CNO, O.ONO;
